{% set version = '1.1.0' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-cuperdec
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/cuperdec_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/cuperdec/cuperdec_{{ version }}.tar.gz
  sha256: 3c3676424b13c32cd666ff5316ecbd2e7a94b7b140d4d6fbef68dc36d65c73ef

build:
  merge_build_host: True  # [win]
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-dplyr
    - r-ggplot2
    - r-magrittr
    - r-readr
    - r-rlang
    - r-tidyr
  run:
    - r-base
    - r-dplyr
    - r-ggplot2
    - r-magrittr
    - r-readr
    - r-rlang
    - r-tidyr

test:
  commands:
    - $R -e "library('cuperdec')"           # [not win]
    - "\"%R%\" -e \"library('cuperdec')\""  # [win]

about:
  home: https://github.com/jfy133/cuperdec
  license: MIT
  summary: Calculates and visualises cumulative percent 'decay' curves, which are typically calculated
    from metagenomic taxonomic profiles. These can be used to estimate the level of
    expected 'endogenous' taxa at different abundance levels retrieved from metagenomic
    samples, when comparing to samples of known sampling site or source. Method described
    in Fellows Yates, J. A. et. al. (2021) Proceedings of the National Academy of Sciences
    USA <doi:10.1073/pnas.2021655118>.
  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE
# Type: Package

extra:
  recipe-maintainers:
    - conda-forge/r
    - jfy133

# Package: cuperdec
# Title: Cumulative Percent Decay Curve Generator
# Version: 1.1.0
# Authors@R: person(given = "James A.", family = "Fellows Yates", role = c("aut", "cre"), email = "jfy133@gmail.com", comment = c(ORCID = "0000-0001-5585-6277"))
# Description: Calculates and visualises cumulative percent 'decay' curves, which are typically calculated from metagenomic taxonomic profiles. These can be used to estimate the level of expected 'endogenous' taxa at different abundance levels retrieved from metagenomic samples, when comparing to samples of known sampling site or source. Method described in Fellows Yates, J. A. et. al. (2021) Proceedings of the National Academy of Sciences USA <doi:10.1073/pnas.2021655118>.
# License: MIT + file LICENSE
# URL: https://github.com/jfy133/cuperdec
# BugReports: https://github.com/jfy133/cuperdec/issues
# Depends: R (>= 3.5.0)
# Imports: dplyr, ggplot2, magrittr, readr, rlang, tidyr
# Suggests: knitr, rmarkdown, testthat, tibble
# VignetteBuilder: knitr
# Encoding: UTF-8
# Language: en-GB
# LazyData: true
# NeedsCompilation: no
# RoxygenNote: 7.1.2
# Packaged: 2021-09-12 18:12:11 UTC; jfellows
# Author: James A. Fellows Yates [aut, cre] (<https://orcid.org/0000-0001-5585-6277>)
# Maintainer: James A. Fellows Yates <jfy133@gmail.com>
# Repository: CRAN
# Date/Publication: 2021-09-12 21:40:10 UTC
